### ISSUE TITLE
setup stripe account and launch booking engine.

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#202]

**Comment by atharva3010** [comment]
@mort3za 
- You may need to check the endpoints for reservations and update them in the client app if needed.
- There is a need for the creation of a thank you page with the booking info, to be displayed right after receiving confirmation from the API.
- There are some design issues when browsing on safari, on the accommodation page. Please check on browserstack, the user has to scroll down to see contents, there is a lot of whitespace on top.
- You may need to coordinate with @StrangeWill for receiving a list of available dates for each property and then block them in the `AirbnbStyleDatepicker`. You can read it's documentation to understand how to block specific dates https://github.com/MikaelEdebro/vue-airbnb-style-datepicker
- Designwise all other requirements have been fulfilled, IDK if there are any new design changes.
- You need to setup auth guards on `/reservation/reviewrules` & `/reservation/confirmandpay` so that these pages can only be accessed only when the form is filled and user is authed.
