### ISSUE TITLE
switch home page to api

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#365]
We added home page to our api to allow us to edit the custom JSON for SEO. Please use this for the home page:

https://stagingapi.whynot.earth/api/v0/pages/slug/vkirirom/Home

**Comment by mort3za** [comment]
Some image URLs have problem because of wrong transformations in mentioned API request.  
I applied custom field to listing and search pages too.  
It's better to move main site title AFTER pipe I think, because browsers hide the right part on tabs. But if you disagree, let me know to change it in *title tag* too.

**Comment by paulchrisluke** [comment]
We can remove all transformations in the database, probably better that way anyway. I'll get an issue out for that...

We will also change the json for SEO to add title AFTER pipe. Thanks for the good work!

**Comment by paulchrisluke** [comment]
@mort3za the database has been updated to your suggestions if you want to make this change now
