### ISSUE TITLE
Mobile Log In Issue

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#385]
Our current booking flow includes a log-in screen 
However, testing our booking flow on mobile:
- safari, iphone 8
- chrome, iphone 8

we are unable to progress past login screen, both with @mort3za 's test account and with a separate gmail account through google login. Google's redirect log in process worked, but is not reflected once you are redirected back to our site

https://deploy-preview-384--cranky-nightingale-3731fc.netlify.com/
![image1](https://user-images.githubusercontent.com/5694308/73736516-76e8c980-4773-11ea-8c1b-d65f09f903f9.png)
![image0 (1)](https://user-images.githubusercontent.com/5694308/73736572-94b62e80-4773-11ea-8d68-9e838f5b4bc7.png)

This issue continues as we exit the booking flow and try to log in through the navigation as well, where the login does not actually happen 
![image0 (2)](https://user-images.githubusercontent.com/5694308/73736774-f7a7c580-4773-11ea-939b-480dd957051f.png)

Login has been fine with: 
- Firefox Desktop
- Chrome Desktop

**Comment by mort3za** [comment]
Related conversation on discord:

Test on iPhone :point_down:  
![unknown](https://user-images.githubusercontent.com/510242/74128001-61e7bc80-4bf1-11ea-887c-48699265048f.png)

Only one set-cookie (not auth)    
![Screenshot_from_2020-02-08_01-58-47](https://user-images.githubusercontent.com/510242/74128018-6c09bb00-4bf1-11ea-8d48-f7e9efd04a81.png)

same request (devtools: header tab)  
![Screenshot_from_2020-02-08_01-59-08](https://user-images.githubusercontent.com/510242/74128030-71ff9c00-4bf1-11ea-9172-d6cffbbdcf3a.png)

Now, see the chrome desktop's response of login :point_down:  
Here we have two set-cookie (including auth)  
![unknown (1)](https://user-images.githubusercontent.com/510242/74128044-7d52c780-4bf1-11ea-8eab-900cfed170b1.png)

![unknown (2)](https://user-images.githubusercontent.com/510242/74128060-8774c600-4bf1-11ea-878c-a66aa48103a3.png)


Do you think that the problem is related to SameSite=Lax?  Maybe Safari iOS can't understand it

If Safari isn't understanding it, it shouldn't enforce it
(The SameSite feature entirely that is)
that is interesting though hmm
We use the exact same auth method on a PWA we've had in production for a few months now
So doubly hmm
what we did have was iOS being very eager to kill session cookies when swapping between apps
but that should still get the same cookie back
oh no
both cookies are in there

why both cookies are being passed in one header is a bit weird
that used to be valid, long ago
The question is who is right:
Is chrome getting two cookie headers or is it displaying two when only getting one?
I'd say to run something like Fiddler and scrape the HTTPS traffic and see which is true

or: is chrome being handed two cookies and Safari one for some weird-ass reason

**Comment by ctyar** [comment]
Raw response to `/api/v0/authentication/login`:
[Raw.txt](https://github.com/whynotearth/hotel-website-vkirirom.com/files/4179562/Raw.txt)

**Comment by mort3za** [comment]
@StrangeWill

**Comment by ctyar** [comment]
Summary of my findings up until now:

`Login` request is always successful and has a valid cookie but the next request `ping` doesn't have/use the cookie so it fails

![login](https://user-images.githubusercontent.com/1432648/74323678-238e0100-4d9b-11ea-9169-88ef93df84c0.png)

**Comment by StrangeWill** [comment]
Is the iOS browser debugger showing the `auth` cookie set or missing? If it's set than it's the Vue client not liking something (though we are sending that credentials are allowed so not sure what else it could be ), if it's not set it's for some reason reading that cookie and possibly immediately expiring it?

**Comment by StrangeWill** [comment]
So: if we start the oauth flow, cancel it, and log in. Works fine on iOS, including all future logins.

**Comment by StrangeWill** [comment]
https://github.com/axios/axios/issues/1224
and by extension
https://webkit.org/blog/7675/intelligent-tracking-prevention/

**Comment by paulchrisluke** [comment]
Currently on iphone chrome browser (normal and incognito), log in does not work for Facebook or Google. Logging into a vkirirom specific account works, and users are able to continue browsing the site or continue booking. 

Logging in directly from the menu is unsuccessful, and just leads to reload of the log in pop-up
Logging in through the booking flow is unsuccessful and leaves users unable to progress past "log in" part of booking flow on the site. 

For both facebook and google, pressing their respective log in buttons the **first time** will lead to redirect to their respective log in pages 
![image0](https://user-images.githubusercontent.com/5694308/74798968-d9a89c00-5301-11ea-8840-28ecaa3bb5de.png)
![image1](https://user-images.githubusercontent.com/5694308/74799012-f7760100-5301-11ea-95df-10b365e8e44d.png)

After successfully inputting your account information for Facebook or Google, you are redirected back to vkirirom's log-in pop up.
![image0](https://user-images.githubusercontent.com/5694308/74799539-61db7100-5303-11ea-9f94-cb21398b2698.png)

Pressing the Facebook or Google buttons to re-attempt log in (without refreshing) will only lead to reloading of pop-up, and not anymore redirects 

Refreshing the page will also not redirect to Facebook or Google log in flow after pressing the button (after the first time you are redirected). 

There is a similar issue with the "sign up" flow
Pressing "sign up with Facebook" or "sign up with google" the first time will lead to the Facebook/Google log in flow, but any time after that will open the vkirirom log in pop-up instead, and continue with the same issue as described above

**Comment by mort3za** [comment]
I can't login even on Chrome desktop, either by email or by OAuth. @ctyar

**Comment by paulchrisluke** [comment]
This is urgent, it's preventing conversions .

**Comment by paulchrisluke** [comment]
The same behavior is still happening on chrome for incognito mobile, both on develop.vkirirom.com and vkirirom.com

This is the same for Facebook and Google log in

**Comment by StrangeWill** [comment]
I'm not seeing a JWT token in the ping request -- is there another URL to test JWT with?

**Comment by mort3za** [comment]
![image](https://user-images.githubusercontent.com/510242/75420083-74c9f300-594c-11ea-920e-c673e2e7d5bc.png)

Also tested on chrome mobile incognito on android, desktop incognito.  
@StrangeWill All other requests have jwt token but we only use it in ping.
