### ISSUE TITLE
GET https://api.whynot.earth/api/v0/roomtypes/55/prices?startDate=2020-09-03&endDate=2020-09-05 404

### ISSUE THREAD

**Issue by sotheaYouk** [whynotearth/hotel-website-vkirirom.com#479]
the choose dates page keeps loading and nothing shows up after selecting the check in and check out dates
https://vkirirom.com/listing/Bungalow
@paulchrisluke

**Comment by sotheaYouk** [comment]
os: Windows 10 & IOS 13.4.1
browser: Chrome and Safari 
no error messages. 
![video-to-gif-converter](https://user-images.githubusercontent.com/34526910/88995703-9113f680-d315-11ea-9387-d0277c13adb8.gif)

**Comment by paulchrisluke** [comment]
GET https://api.whynot.earth/api/v0/roomtypes/55/prices?startDate=2020-09-03&endDate=2020-09-05 404

https://github.com/whynotearth/meredith-core/commit/0c1fdc76b0ce0333b36c4f852a98062882a573b8


A contributor wrote an endpoint which does create a price for a date and it has no authentication... may be causing an issue with prices not displaying on https://vkirirom.com 
Its calling it over and over can create a lot of prices in db. I don't see any exceptions in RollBar though. 

Current endpoint:
https://github.com/whynotearth/meredith-core/blob/staging/WhyNotEarth.Meredith.App/Controllers/Api/v0/Hotel/PriceController.cs

**Comment by sotheaYouk** [comment]
**Steps to reproduce** 
1. Go to 'https://vkirirom.com/listing/Bell-Tent'
2. Scroll to "Book Now"
3. Pick dates "Sep 3 & Sep 5, 2020"
4. The page keeps loading as it displays "Failed to load resource: the server responded with a status of 404"

**Desktop**
- Browser: Chrome
- OS: Windows  
![image](https://user-images.githubusercontent.com/34526910/89022152-c20f1e00-d34b-11ea-9a62-6d076df6a490.png)

**Comment by paulchrisluke** [comment]
https://github.com/whynotearth/hotel-website-vkirirom.com/issues/479
The Api endpoint is wrong here. It should be api/v0/hotel/roomtypes/55/prices?startDate=2020-09-03&endDate=2020-09-05 instead of
api/v0/roomtypes/55/prices?startDate=2020-09-03&endDate=2020-09-05 

'/hotel' is missing in the vue service
GitHub
GET https://api.whynot.earth/api/v0/roomtypes/55/prices?startDate=2...
the choose dates page keeps loading and nothing shows up after selecting the check in and check out dates https://vkirirom.com/listing/Bungalow @paulchrisluke

https://github.com/whynotearth/hotel-website-vkirirom.com/blob/master/src/connection/resources.js
Navigate to line 435 in the vue app -> connection -> resources.js

**Comment by paulchrisluke** [comment]
@sotheaYouk date issue is fixed here: https://github.com/whynotearth/hotel-website-vkirirom.com/commit/fa3484eb53a56a4b8b03d4c234ffffba9c7ffbeb

you can test on https://vkirirom.com

However, there is an issue with login on the next step. Can you please create a bug issue for that and we can work on it?

**Comment by paulchrisluke** [comment]
@sotheaYouk this is resolved. Please test and confirm, and close the issue if working

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/89487091-d5e4d500-d7ce-11ea-9067-919e3c6409a7.png)
